export const COUNTRY = [
  { value: "AE", label: "阿联酋" },
  { value: "AR", label: "阿根廷" },
  { value: "AT", label: "奥地利" },
  { value: "AU", label: "澳大利亚" },
  { value: "BD", label: "孟加拉国" },
  { value: "BE", label: "比利时" },
  { value: "BG", label: "保加利亚" },
  { value: "BH", label: "巴林" },
  { value: "BO", label: "玻利维亚" },
  { value: "BR", label: "巴西" },
  { value: "BY", label: "白俄罗斯" },
  { value: "CA", label: "加拿大" },
  { value: "CH", label: "瑞士" },
  { value: "CL", label: "智利" },
  { value: "CO", label: "哥伦比亚" },
  { value: "CR", label: "哥斯达黎加" },
  { value: "CZ", label: "捷克" }, // 注意：通常应为'CZ' => '捷克共和国'
  { value: "DE", label: "德国" },
  { value: "DK", label: "丹麦" },
  { value: "DO", label: "多米尼加" },
  { value: "DZ", label: "阿尔及利亚" },
  { value: "EC", label: "厄瓜多尔" },
  { value: "EG", label: "埃及" },
  { value: "ES", label: "西班牙" },
  { value: "FI", label: "芬兰" },
  { value: "FR", label: "法国" },
  { value: "GB", label: "英国" },
  { value: "GR", label: "希腊" },
  { value: "GT", label: "危地马拉" }, // 注意：应为'危地马拉共和国'
  { value: "HU", label: "匈牙利" },
  { value: "ID", label: "印度尼西亚" },
  { value: "IE", label: "爱尔兰" },
  { value: "IL", label: "以色列" },
  { value: "IQ", label: "伊拉克" },
  { value: "IT", label: "意大利" },
  { value: "JP", label: "日本" },
  { value: "KH", label: "柬埔寨" },
  { value: "KR", label: "韩国" },
  { value: "KW", label: "科威特" },
  { value: "KZ", label: "哈萨克斯坦" },
  { value: "LA", label: "老挝" },
  { value: "LB", label: "黎巴嫩" },
  { value: "MA", label: "摩洛哥" },
  { value: "MX", label: "墨西哥" },
  { value: "MY", label: "马来西亚" },
  { value: "NL", label: "荷兰" },
  { value: "NO", label: "挪威" },
  { value: "NZ", label: "新西兰" },
  { value: "OM", label: "阿曼" },
  { value: "PE", label: "秘鲁" },
  { value: "PH", label: "菲律宾" },
  { value: "PK", label: "巴基斯坦" },
  { value: "PL", label: "波兰" },
  { value: "PR", label: "波多黎各" },
  { value: "PT", label: "葡萄牙" },
  { value: "PY", label: "巴拉圭" },
  { value: "QA", label: "卡塔尔" },
  { value: "RO", label: "罗马尼亚" },
  { value: "SA", label: "沙特阿拉伯" },
  { value: "SE", label: "瑞典" },
  { value: "SG", label: "新加坡" },
  { value: "TH", label: "泰国" },
  { value: "TR", label: "土耳其" },
  { value: "TW", label: "中国台湾" }, // 注意：ISO 3166-1 不包含“中国台湾”
  { value: "US", label: "美国" },
  { value: "UY", label: "乌拉圭" },
  { value: "VN", label: "越南" },
  { value: "ZA", label: "南非" },
  // 如果需要添加更多国家，可以在这里继续添加
  // { value: 'ZZ', label: '某个国家' }, // 示例：添加一个新国家（假设ZZ是某个虚构的国家代码）
];

export const OBJECTIVES = [
  { value: "traffic", label: "访问量" },
  { value: "app installs", label: "应用安装量" },
  { value: "conversations", label: "转化量" },
  { value: "video_views", label: "视频播放量" },
  { value: "reach", label: "覆盖人数" },
  { value: "lead generation", label: "潜在用户拓展" },
  { value: "product sales", label: "商品销售" },
];
